[tool.poetry]
name = "neon-hub-config"
version = "0.1.0"
description = "Neon Hub Configuration Tool"
authors = ["Oscillate Labs <mike@oscillatelabs.net>"]
license = "BSD-3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.141.1"
starlette = "^1.3.1"
ovos-bus-client = "^0.1.4"
ovos-workshop = "^1.0.2"
ovos-utils = "^0.3.5"
uvicorn = "^0.32.0"
json-database = "^0.7.0"
ruamel-yaml = "^0.18.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
